name: Build 2023 2024
on: [workflow_dispatch, push]
jobs:
  build_2023_2024:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Restore Packages
        run: nuget restore RevitDataValidator.sln
        env:
          NUGET_RESTORE_MSBUILD_ARGS: /p:Configuration=2023
      - name: Build solution
        run: msbuild RevitDataValidator.sln -t:rebuild -property:Configuration=2023
      - name: Restore Packages
        run: nuget restore RevitDataValidator.sln
        env:
          NUGET_RESTORE_MSBUILD_ARGS: /p:Configuration=2024
      - name: Build solution
        run: msbuild RevitDataValidator.sln -t:rebuild -property:Configuration=2024
  build_2025:
      runs-on: windows-2022
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup MSBuild
          uses: microsoft/setup-msbuild@v1
        - name: Setup NuGet
          uses: NuGet/setup-nuget@v1.0.5
        - name: setup-msbuild
          uses: microsoft/setup-msbuild@v1.1
        - name: Restore Packages
          run: nuget restore RevitDataValidator.sln
          env:
            NUGET_RESTORE_MSBUILD_ARGS: /p:Configuration=2025
        - name: Build solution
          run: msbuild RevitDataValidator.sln -t:rebuild -property:Configuration=2025    
  advinst-aip-build-demo:
    runs-on: windows-latest
    name: Build Aip Demo
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build AIP
        uses: caphyon/advinst-github-action@v1.0
        with:
          advinst-version: '21.2.2'
          advinst-license: ${{ secrets.ADVINST_LICENSE_KEY }}
          advinst-enable-automation: 'true'
          aip-path: ${{ github.workspace }}\RevitDataValidator.aip
          aip-build-name: DefaultBuild
          aip-package-name: setup.msi
          aip-output-dir:  ${{ github.workspace }}\setup
          aip-commands: |
            SetProperty FOO="foo"
            SetVersion 1.2.0
      - name: Publish setup artifact
        uses: actions/upload-artifact@v2
        with:
          name: setup
          path: ${{ github.workspace }}\setup\setup.msi
